modLoader = "kotlinforforge"
loaderVersion = "[1.6,)"
license = "LGPL-3.0"
[[mods]]
modId = "ingameime"
version = "${file.jarVersion}"
displayName = "IngameIME"
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/Windmill-City/IngameIME-Minecraft"
logoFile = "../icon.png"
authors = "Windmill_City"
description = '''
Enable IME in FullScreen Minecraft
'''
[[dependencies.ingameime]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.ingameime]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,1.17)"
ordering = "NONE"
side = "CLIENT"
